stages:
  - example

variables:
  LC_ALL: "fr_FR.UTF-8"
  LANG: "fr_FR.UTF-8"

before_script:
  - bundle install --path vendor/bundle


beta:
  dependencies: []
  stage: example
  script:
    - bundle exec fastlane example
  tags:
    - gitlab-org
  only:
    - main


