# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)


platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Example Build from dev to firebase"
  lane :example do

        gradle(
            task: "clean assemble",
            build_type: 'devDebug'
        )

        firebase_app_distribution(
            app: "1:620484188434:android:da71ecf6e6941349ae7bcb",
            service_credentials_file: "firebase_credentials.json",
            groups: "me",
            android_artifact_type: "APK"
        )

  end

  desc "Build debug and test APK for screenshots"
  lane :build_and_screengrab do
    build_android_app(
      task: 'clean assemble',
      build_type: 'devDebug'
    )
    build_android_app(
      task: 'clean assemble',
      build_type: 'AndroidTest'
    )
    screengrab()
  end

end
